"""create core tables

Revision ID: 3d4526765c0a
Revises: 
Create Date: 2026-05-26 17:34:49.411148
"""
from alembic import op
import sqlalchemy as sa


revision = '3d4526765c0a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor', sa.String(length=120), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=False),
    sa.Column('details_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    op.create_table('metric_definitions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('metric_name', sa.String(length=120), nullable=False),
    sa.Column('formula', sa.Text(), nullable=False),
    sa.Column('source_fields', sa.Text(), nullable=False),
    sa.Column('time_grain', sa.String(length=40), nullable=False),
    sa.Column('currency_rule', sa.String(length=120), nullable=False),
    sa.Column('version', sa.String(length=40), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_definitions')),
    sa.UniqueConstraint('metric_name', 'version', name=op.f('uq_metric_definitions_metric_name'))
    )
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=80), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations')),
    sa.UniqueConstraint('slug', name=op.f('uq_organizations_slug'))
    )
    op.create_table('daily_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('report_version', sa.Integer(), nullable=False),
    sa.Column('data_version', sa.String(length=120), nullable=False),
    sa.Column('metric_definition_version', sa.String(length=40), nullable=False),
    sa.Column('prompt_version', sa.String(length=40), nullable=False),
    sa.Column('model_name', sa.String(length=120), nullable=False),
    sa.Column('report_json', sa.Text(), nullable=False),
    sa.Column('markdown', sa.Text(), nullable=False),
    sa.Column('excel_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_daily_reports_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_reports')),
    sa.UniqueConstraint('organization_id', 'report_date', 'report_version', name=op.f('uq_daily_reports_organization_id'))
    )
    op.create_table('seller_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('amazon_seller_id', sa.String(length=80), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_seller_accounts_organization_id_organizations')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_seller_accounts')),
    sa.UniqueConstraint('organization_id', 'amazon_seller_id', name=op.f('uq_seller_accounts_organization_id'))
    )
    op.create_table('marketplaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_account_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_id', sa.String(length=80), nullable=False),
    sa.Column('region', sa.String(length=40), nullable=False),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('timezone', sa.String(length=80), nullable=False),
    sa.Column('currency_code', sa.String(length=3), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['seller_account_id'], ['seller_accounts.id'], name=op.f('fk_marketplaces_seller_account_id_seller_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_marketplaces')),
    sa.UniqueConstraint('seller_account_id', 'marketplace_id', name=op.f('uq_marketplaces_seller_account_id'))
    )
    op.create_table('daily_metrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_account_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('metric_date', sa.Date(), nullable=False),
    sa.Column('metric_name', sa.String(length=120), nullable=False),
    sa.Column('metric_value', sa.Numeric(precision=16, scale=4), nullable=False),
    sa.Column('metric_version', sa.String(length=40), nullable=False),
    sa.Column('data_status', sa.String(length=40), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], name=op.f('fk_daily_metrics_marketplace_id_marketplaces')),
    sa.ForeignKeyConstraint(['seller_account_id'], ['seller_accounts.id'], name=op.f('fk_daily_metrics_seller_account_id_seller_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_metrics')),
    sa.UniqueConstraint('seller_account_id', 'marketplace_id', 'metric_date', 'metric_name', name=op.f('uq_daily_metrics_seller_account_id'))
    )
    op.create_table('import_jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seller_account_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('report_type', sa.String(length=80), nullable=False),
    sa.Column('date_range_start', sa.Date(), nullable=False),
    sa.Column('date_range_end', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('error_code', sa.String(length=80), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], name=op.f('fk_import_jobs_marketplace_id_marketplaces')),
    sa.ForeignKeyConstraint(['seller_account_id'], ['seller_accounts.id'], name=op.f('fk_import_jobs_seller_account_id_seller_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_import_jobs'))
    )
    op.create_table('raw_datasets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('import_job_id', sa.Integer(), nullable=False),
    sa.Column('seller_account_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('report_type', sa.String(length=80), nullable=False),
    sa.Column('date_range_start', sa.Date(), nullable=False),
    sa.Column('date_range_end', sa.Date(), nullable=False),
    sa.Column('schema_version', sa.String(length=80), nullable=False),
    sa.Column('raw_file_path', sa.String(length=500), nullable=False),
    sa.Column('raw_file_checksum', sa.String(length=128), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('data_status', sa.String(length=40), nullable=False),
    sa.Column('data_version', sa.String(length=120), nullable=False),
    sa.Column('source_generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['import_job_id'], ['import_jobs.id'], name=op.f('fk_raw_datasets_import_job_id_import_jobs')),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], name=op.f('fk_raw_datasets_marketplace_id_marketplaces')),
    sa.ForeignKeyConstraint(['seller_account_id'], ['seller_accounts.id'], name=op.f('fk_raw_datasets_seller_account_id_seller_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_datasets')),
    sa.UniqueConstraint('seller_account_id', 'marketplace_id', 'report_type', 'raw_file_checksum', name=op.f('uq_raw_datasets_seller_account_id'))
    )
    op.create_table('normalized_business_daily',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_dataset_id', sa.Integer(), nullable=False),
    sa.Column('seller_account_id', sa.Integer(), nullable=False),
    sa.Column('marketplace_id', sa.Integer(), nullable=False),
    sa.Column('report_date', sa.Date(), nullable=False),
    sa.Column('asin', sa.String(length=20), nullable=True),
    sa.Column('sku', sa.String(length=120), nullable=True),
    sa.Column('ordered_product_sales', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('units_ordered', sa.Integer(), nullable=False),
    sa.Column('sessions', sa.Integer(), nullable=False),
    sa.Column('page_views', sa.Integer(), nullable=False),
    sa.Column('conversion_rate', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.Column('buy_box_percentage', sa.Numeric(precision=8, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['marketplace_id'], ['marketplaces.id'], name=op.f('fk_normalized_business_daily_marketplace_id_marketplaces')),
    sa.ForeignKeyConstraint(['raw_dataset_id'], ['raw_datasets.id'], name=op.f('fk_normalized_business_daily_raw_dataset_id_raw_datasets')),
    sa.ForeignKeyConstraint(['seller_account_id'], ['seller_accounts.id'], name=op.f('fk_normalized_business_daily_seller_account_id_seller_accounts')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_normalized_business_daily'))
    )
    op.create_table('raw_report_rows',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('raw_dataset_id', sa.Integer(), nullable=False),
    sa.Column('row_number', sa.Integer(), nullable=False),
    sa.Column('row_json', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['raw_dataset_id'], ['raw_datasets.id'], name=op.f('fk_raw_report_rows_raw_dataset_id_raw_datasets')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_report_rows'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('raw_report_rows')
    op.drop_table('normalized_business_daily')
    op.drop_table('raw_datasets')
    op.drop_table('import_jobs')
    op.drop_table('daily_metrics')
    op.drop_table('marketplaces')
    op.drop_table('seller_accounts')
    op.drop_table('daily_reports')
    op.drop_table('organizations')
    op.drop_table('metric_definitions')
    op.drop_table('audit_logs')
    # ### end Alembic commands ###
